### PR TITLE
testing

### PR DESCRIPTION
**Pull request by samuelchong**
@tintoy Could you provide some guide to running the Acceptance test? 
When running 'make testacc' , all the tests failed with 

testing.go:548: Step 0 error: config is invalid: 2 problems:
                - "cloudcontrol_endpoint": conflicts with region
                - "region": conflicts with cloudcontrol_endpoint

How to define provider.ddcloud for test?

### CODE REVIEW

**Comment by tintoy** [comment]
That message means you can specify `cloudcontrol_endpoint` in the config HCL (e.g. [as shown here](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.3/ddcloud/datasource_networkdomain_test.go#L17-L19)), or you can specify `region`, but you can't specify both at once.

**Comment by tintoy** [comment]
(as specified [here](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/13b1f3e84a4225e88d912fadd54886e8253c8565/ddcloud/provider.go#L28) and [here](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/13b1f3e84a4225e88d912fadd54886e8253c8565/ddcloud/provider.go#L35)).

**Comment by samuelchong** [comment]
Thx @tintoy. All the tests specify region only; for some reason it still thinks that region and cloudcontrol_endpoint are both defined.  I had to comment out 
https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/13b1f3e84a4225e88d912fadd54886e8253c8565/ddcloud/provider.go#L28 and https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/13b1f3e84a4225e88d912fadd54886e8253c8565/ddcloud/provider.go#L35 as a temporary workaround while executing the test. 



...
=== RUN   TestAccVirtualListenerBasicUpdateName
--- FAIL: TestAccVirtualListenerBasicUpdateName (0.02s)
        testing.go:548: Step 0 error: config is invalid: 2 problems:

                - "region": conflicts with cloudcontrol_endpoint
                - "cloudcontrol_endpoint": conflicts with region
=== RUN   TestAccVLANBasicCreate
--- FAIL: TestAccVLANBasicCreate (0.02s)
        testing.go:548: Step 0 error: config is invalid: 2 problems:

                - "region": conflicts with cloudcontrol_endpoint
                - "cloudcontrol_endpoint": conflicts with region
=== RUN   TestAccVLANBasicUpdate
--- FAIL: TestAccVLANBasicUpdate (0.01s)
        testing.go:548: Step 0 error: config is invalid: 2 problems:

                - "cloudcontrol_endpoint": conflicts with region
                - "region": conflicts with cloudcontrol_endpoint
...

**Comment by tintoy** [comment]
Maybe because both have a default value that isn’t `nil`?

**Comment by samuelchong** [comment]
that might be the case. Will look into that when I've got a bit of time. Thx @tintoy

**Pull request merged**
