### PR TITLE
Merge for new release  

### PR DESCRIPTION
**Pull request by samuelchong**
create release for features added: datasource addresslist, resource address, bug fix

### CODE REVIEW

**Comment by samuelchong** [comment]
Travis failed. Any idea? 

...
../../hashicorp/terraform/plans/planfile/writer.go:52:12: unknown field 'Modified' in struct literal of type zip.FileHeader
The command "go get github.com/hashicorp/terraform" failed and exited with 2 during .
Your build has been stopped.

**Comment by tintoy** [comment]
What version of go is being used for CI?

**Comment by samuelchong** [comment]
Travis passed now. Issue fixed using go 1.10. It was previously using 1.9

**Comment by tintoy** [comment]
Yeah, the folks at Hashicorp (and the go community in general) tend to always use latest everything 😉)

**Comment by samuelchong** [comment]
Thx @tintoy 
I know it's a big ask. I will attempt to carry on the good work you've started. Not many people here understand this project enough to do a code review for me. I am doing an upgrade of cloud control api and add more new features in the near future. You are always welcome to comment, feedback, review or criticise any code checkin, anytime  :)

**Comment by tintoy** [comment]
No worries, it was one of the first open source projects I started - happy to help out where I can :)

**Pull request merged**
